//const xyz = require('./people')
const {people,ages} = require('./people')
//console.log(xyz)
console.log(people,ages)
//console.log(xyz.ages)
//console.log(xyz.people)
const os=require('os')
//console.log(os)
console.log(os.platform(),os.homedir(),os.hostname())